using DocumentFormat.OpenXml.InkML;
using FleetManager.Domain.Models;
using FleetManager.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace FleetManager.WebMVC.Controllers
{
    [Authorize]

    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly FleetContext _context;

        public UsersController(FleetContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var fleetContext = _context.Users.Include(u => u.Role);
            return View(await fleetContext.ToListAsync());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (user == null) return NotFound();

            return View(user);
        }

        [Authorize(Roles = "superadmin,admin")]
        public IActionResult Create()
        {
            var roles = _context.Roles.AsQueryable();

            if (User.IsInRole("admin"))
            {
                roles = roles.Where(r => r.Name == "user");
            }

            ViewData["RoleId"] = new SelectList(roles, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> Create([Bind("UserName,Email,PasswordHash,FullName,IsActive,RoleId")] User user)
        {

            ModelState.Remove("Role");

            if (string.IsNullOrWhiteSpace(user.UserName))
            {
                ModelState.AddModelError("UserName", "Логін є обов'язковим");
            }

            if (ModelState.IsValid)
            {

                var selectedRole = await _context.Roles.FindAsync(user.RoleId);
                if (User.IsInRole("admin") && selectedRole != null && selectedRole.Name != "user")
                {
                    ModelState.AddModelError("RoleId", "Адміністратор може створювати лише користувачів з роллю 'user'.");
                }


                if (selectedRole != null && selectedRole.Name == "superadmin")
                {
                    var existingInIdentity = await _userManager.GetUsersInRoleAsync("superadmin");
                    var existingInTable = _context.Users.Include(u => u.Role).Any(u => u.Role != null && u.Role.Name == "superadmin");
                    if (existingInIdentity.Any() || existingInTable)
                    {
                        ModelState.AddModelError("RoleId", "В системі вже існує суперадміністратор. Неможливо створити ще одного.");
                    }
                }

                if (selectedRole != null && selectedRole.Name == "admin")
                {
                    if (string.IsNullOrWhiteSpace(user.Email))
                    {
                        ModelState.AddModelError("Email", "Email є обов'язковим для акаунтів з роллю admin або superadmin.");
                    }
                }

                if (!ModelState.IsValid)
                {
                    ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                    return View(user);
                }

                var newUser = new User
                {
                    UserName = user.UserName,
                    Email = string.IsNullOrWhiteSpace(user.Email) ? user.UserName : user.Email,
                    FullName = user.FullName,
                    IsActive = user.IsActive ?? true,
                    RoleId = user.RoleId,
                    CreatedAt = DateTime.UtcNow
                };


                var passwordToUse = user.PasswordHash;
                var autoGenerated = false;
                if (string.IsNullOrWhiteSpace(passwordToUse))
                {
                    if (selectedRole != null && selectedRole.Name == "admin")
                    {
                        passwordToUse = GenerateRandomPassword();
                        autoGenerated = true;
                    }
                    else
                    {
                        ModelState.AddModelError("PasswordHash", "Пароль є обов'язковим для цього типу користувача.");
                        ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                        return View(user);
                    }
                }

                var createResult = await _userManager.CreateAsync(newUser, passwordToUse);

                if (createResult.Succeeded)
                {

                    if (selectedRole != null)
                    {
                        await _userManager.AddToRoleAsync(newUser, selectedRole.Name);
                    }

                    if (autoGenerated)
                    {
                        var emailSender = HttpContext.RequestServices.GetService(typeof(FleetManager.WebMVC.Services.IEmailSender)) as FleetManager.WebMVC.Services.IEmailSender;
                        if (emailSender != null && !string.IsNullOrWhiteSpace(newUser.Email))
                        {
                            try
                            {
                                await emailSender.SendEmailAsync(newUser.Email, "Ваш пароль для входу", $"Ваш тимчасовий пароль: {passwordToUse}");
                                TempData["InfoMessage"] = "Користувача створено. Пароль було згенеровано і надіслано на вказаний email.";
                            }
                            catch
                            {
                                TempData["InfoMessage"] = "Користувача створено. Пароль згенеровано, але не вдалося надіслати email (перевірте SMTP).";
                            }
                        }
                        else
                        {
                            TempData["InfoMessage"] = "Користувача створено. Пароль згенеровано, але email не вказано.";
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in createResult.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
            return View(user);
        }

        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null) return NotFound();

            var user = await _context.Users.FindAsync(id);
            if (user == null) return NotFound();

            var currentUserId = _userManager.GetUserId(User);

            if (User.IsInRole("superadmin") && user.Id == currentUserId)
            {
                TempData["ErrorMessage"] = "Ви не можете редагувати свій власний профіль суперадміна.";
                return RedirectToAction(nameof(Index));
            }

            if (User.IsInRole("admin"))
            {
                if (await _userManager.IsInRoleAsync(user, "superadmin") || await _userManager.IsInRoleAsync(user, "admin"))
                {
                    TempData["ErrorMessage"] = "Ви не можете редагувати профілі адміністраторів або суперадміністратора.";
                    return RedirectToAction(nameof(Index));
                }
            }

            var roles = _context.Roles.AsQueryable();

            if (User.IsInRole("admin"))
            {
                roles = roles.Where(r => r.Name == "user");
            }

            ViewData["RoleId"] = new SelectList(roles, "Id", "Name", user.RoleId);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserName,PasswordHash,FullName,IsActive,RoleId,Email")] User user)
        {
            if (id != user.Id) return NotFound();

            ModelState.Remove("Role");

            if (string.IsNullOrEmpty(user.PasswordHash))
            {
                ModelState.Remove("PasswordHash");
            }

            if (!string.IsNullOrEmpty(user.UserName) && user.UserName.Trim().ToLower() == "admin")
            {
                var adminExists = await _context.Users.AnyAsync(u => u.UserName.ToLower() == "admin" && u.Id != user.Id);
                if (adminExists)
                {
                    ModelState.AddModelError("UserName", "[ ПОМИЛКА ] Обліковий запис суперадміністратора вже існує!");
                }
            }

            if (string.IsNullOrWhiteSpace(user.UserName))
            {
                ModelState.AddModelError("UserName", "Логін є обов'язковим");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var newRole = await _context.Roles.FindAsync(user.RoleId);
                    if (newRole != null && newRole.Name == "admin" && string.IsNullOrWhiteSpace(user.Email))
                    {
                        ModelState.AddModelError("Email", "Email є обов'язковим для акаунту з роллю admin.");
                        ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                        return View(user);
                    }
                    if (User.IsInRole("admin") && newRole != null && newRole.Name != "user")
                    {
                        ModelState.AddModelError("RoleId", "Адміністратор може призначати лише роль 'user'.");
                        ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                        return View(user);
                    }

                    if (newRole != null && newRole.Name == "superadmin")
                    {
                        var existingSuperadmins = await _userManager.GetUsersInRoleAsync("superadmin");
                        if (existingSuperadmins.Any(u => u.Id != user.Id))
                        {
                            ModelState.AddModelError("RoleId", "В системі вже існує суперадміністратор. Неможливо призначити роль 'superadmin'.");
                            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                            return View(user);
                        }

                        var currentUserId = _userManager.GetUserId(User);
                        if (User.IsInRole("superadmin") && user.Id != currentUserId)
                        {
                            ModelState.AddModelError("RoleId", "Суперадмін не може призначати роль 'superadmin' іншим користувачам.");
                            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                            return View(user);
                        }
                    }

                    var userToUpdate = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
                    if (userToUpdate == null) return NotFound();

                    if (User.IsInRole("admin") && (await _userManager.IsInRoleAsync(userToUpdate, "admin") || await _userManager.IsInRoleAsync(userToUpdate, "superadmin")))
                    {
                        ModelState.AddModelError("", "Ви не маєте прав редагувати адміністратора чи суперадміністратора.");
                        ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                        return View(user);
                    }

                    if (!string.IsNullOrEmpty(userToUpdate.UserName) && userToUpdate.UserName.ToLower() == "admin")
                    {
                        if (user.UserName.ToLower() != "admin" || (newRole != null && newRole.Name != "superadmin"))
                        {
                            ModelState.AddModelError("", "Суперадмін 'admin' є захищеним і не може бути змінений.");
                            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
                            return View(user);
                        }
                    }

                    userToUpdate.UserName = user.UserName;

                    if (!string.IsNullOrEmpty(user.PasswordHash) && user.PasswordHash.Length < 50)
                    {
                        userToUpdate.PasswordHash = HashPassword(user.PasswordHash);
                    }

                    userToUpdate.FullName = user.FullName;
                    userToUpdate.RoleId = user.RoleId;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name", user.RoleId);
            return View(user);
        }

        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound();

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (user == null) return NotFound();


            if (!string.IsNullOrEmpty(user.UserName) && user.UserName.ToLower() == "admin")
            {
                TempData["ErrorMessage"] = "[ СИСТЕМНА ПОМИЛКА ] Неможливо видалити суперадміністратора.";
                return RedirectToAction(nameof(Index));
            }


            if (await _userManager.IsInRoleAsync(user, "superadmin"))
            {
                TempData["ErrorMessage"] = "[ СИСТЕМНА ПОМИЛКА ] Неможливо видалити суперадміністратора.";
                return RedirectToAction(nameof(Index));
            }


            if (User.IsInRole("admin"))
            {
                if (!await _userManager.IsInRoleAsync(user, "user"))
                {
                    TempData["ErrorMessage"] = "Ви не маєте прав видаляти цього користувача.";
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);

            if (user != null)
            {
                if (await _userManager.IsInRoleAsync(user, "superadmin"))
                {
                    var currentUserId = _userManager.GetUserId(User);
                    if (user.Id == currentUserId)
                    {
                        TempData["ErrorMessage"] = "Ви не можете видалити свій власний обліковий запис суперадміна.";
                        return RedirectToAction(nameof(Index));
                    }

                    TempData["ErrorMessage"] = "[ КРИТИЧНА ПОМИЛКА ] Спроба несанкціонованого видалення суперадміна заблокована.";
                    return RedirectToAction(nameof(Index));
                }

                if (User.IsInRole("admin"))
                {
                    if (!await _userManager.IsInRoleAsync(user, "user"))
                    {
                        TempData["ErrorMessage"] = "Ви не маєте прав видаляти цього користувача.";
                        return RedirectToAction(nameof(Index));
                    }
                }

                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }

        private string HashPassword(string password)
        {
            if (string.IsNullOrEmpty(password)) return password;

            using (var sha256 = SHA256.Create())
            {
                var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return BitConverter.ToString(hashedBytes).Replace("-", "").ToLower();
            }
        }

        private string GenerateRandomPassword(int length = 10)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
            var sb = new StringBuilder();
            using (var rng = RandomNumberGenerator.Create())
            {
                var buf = new byte[4];
                while (sb.Length < length)
                {
                    rng.GetBytes(buf);
                    var num = BitConverter.ToUInt32(buf, 0);
                    sb.Append(chars[(int)(num % (uint)chars.Length)]);
                }
            }
            return sb.ToString();
        }

        [HttpPost]
        [Authorize(Roles = "superadmin,admin")]
        public async Task<IActionResult> ToggleStatus(string id, bool isActive)
        {
            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return Json(new { success = false, message = "Користувача не знайдено." });
            }


            if (await _userManager.IsInRoleAsync(user, "superadmin") && !isActive)
            {
                return Json(new { success = false, message = " Неможливо деактивувати суперадміністратора!" });
            }


            if (User.IsInRole("admin"))
            {
                if (!await _userManager.IsInRoleAsync(user, "user"))
                {
                    return Json(new { success = false, message = "Ви не маєте прав змінювати статус цього користувача." });
                }
            }

            user.IsActive = isActive;
            await _context.SaveChangesAsync();

            return Json(new { success = true });
        }
    }
}